export const FETCH_RECOMMENDED = 'FETCH_RECOMMENDED';
export const FETCH_APPLIST = 'FETCH_APPLIST';
export const SET_SCROLLING_FALSE = 'SET_SCROLLING_FALSE';
export const SET_SCROLLING_TRUE = 'SET_SCROLLING_TRUE';


